[common]
seed = 420
engine = "numba"
species = ["H", "C","O"]

[configurations]
training = ["../../../data/ternary/ethanol.xyz"]

[potentials]
initial = "initial.toml"
final = "final.npy"

[loss]
energy_weight = 1.0
forces_weight = 0.05
stress_weight = 0.0

[[steps]]
method = "minimize"

[steps.kwargs]
method = "Nelder-Mead"
tol = 1.0e-6

[steps.kwargs.options]
maxiter = 200
