"""Export tabulated potentials to LAMMPS-compatible files."""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
from typing import Any

import numpy as np
from ase.data import atomic_masses, chemical_symbols
from scipy.interpolate import CubicSpline

from forgeff.potentials.eam.adp_data import ADPData
from forgeff.potentials.eam.data import EAMData
from forgeff.potentials.tersoff.data import TersoffData, TersoffParameters


def _species_labels(species: np.ndarray) -> list[str]:
    return [chemical_symbols[int(number)] for number in np.asarray(species, dtype=int).tolist()]


def _species_masses(species: np.ndarray) -> list[float]:
    return [float(atomic_masses[int(number)]) for number in np.asarray(species, dtype=int).tolist()]


def _species_lattice(species: np.ndarray, lattice: list[str] | None) -> list[str]:
    if lattice is not None:
        if len(lattice) != len(species):
            raise ValueError("Length of lattice metadata must match the number of species.")
        return list(lattice)
    return ["fcc"] * len(species)


def _species_a(species: np.ndarray, a: list[float] | None) -> list[float]:
    if a is not None:
        if len(a) != len(species):
            raise ValueError("Length of lattice constant metadata must match the number of species.")
        return [float(value) for value in a]
    return [1.0] * len(species)


def _write_rows(fd, values: np.ndarray, *, numformat: str = "%.16e", nc: int = 1) -> None:
    arr = np.asarray(values, dtype=float)
    if arr.ndim == 1:
        np.savetxt(fd, arr.reshape(-1, nc), fmt=nc * [numformat])
    else:
        np.savetxt(fd, arr.reshape(arr.shape[0], -1), fmt=arr.shape[1] * [numformat])


def _uniform_grid(grid: np.ndarray, count: int | None) -> np.ndarray:
    source = np.asarray(grid, dtype=float)
    if source.ndim != 1 or source.size < 2:
        raise ValueError("EAM/ADP export requires at least two points on each grid.")
    target_count = int(count) if count is not None else int(source.size)
    if target_count < 2:
        raise ValueError("EAM/ADP export requires at least two points on each exported grid.")
    return np.linspace(0.0, float(source[-1]), target_count, dtype=float)


def _resample_values(source_grid: np.ndarray, values: np.ndarray, target_grid: np.ndarray) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    if arr.shape[-1] != len(source_grid):
        raise ValueError("Grid length does not match the last axis of the tabulated values.")
    spline = CubicSpline(np.asarray(source_grid, dtype=float), arr, axis=-1)
    return np.asarray(spline(target_grid), dtype=float)


def _write_common_header(
    fd,
    data: EAMData | ADPData,
    *,
    r_grid: np.ndarray,
    rho_grid: np.ndarray,
    header: list[str] | None = None,
    lattice: list[str] | None = None,
    a: list[float] | None = None,
    mass: list[float] | None = None,
) -> None:
    species = np.asarray(data.species, dtype=int)
    elements = _species_labels(species)
    masses = list(mass) if mass is not None else _species_masses(species)
    lattices = _species_lattice(species, lattice)
    a_values = _species_a(species, a)

    if header is None:
        header = [
            "LAMMPS setfl format generated by ForgeFF",
            "",
            "",
        ]
    if len(header) < 3:
        header = [*header, *([""] * (3 - len(header)))]
    for line in header[:3]:
        fd.write(f"{line}\n")

    fd.write(f"{len(elements)} {' '.join(elements)}\n")
    fd.write(
        f"{len(rho_grid)} {float(rho_grid[1] - rho_grid[0])} "
        f"{len(r_grid)} {float(r_grid[1] - r_grid[0])} "
        f"{float(r_grid[-1])}\n"
    )


def _write_eam_body(
    fd,
    data: EAMData,
    *,
    r_grid: np.ndarray,
    rho_grid: np.ndarray,
    numformat: str = "%.16e",
) -> None:
    r = np.asarray(r_grid, dtype=float)
    rho = np.asarray(rho_grid, dtype=float)
    species = np.asarray(data.species, dtype=int)
    masses = _species_masses(species)
    lattices = _species_lattice(species, None)
    a_values = _species_a(species, None)

    for i in range(data.species_count):
        fd.write(f"{int(species[i])} {masses[i]:f} {a_values[i]:f} {lattices[i]}\n")
        _write_rows(fd, _resample_values(data.rho_grid, np.asarray(data.emb_values, dtype=float)[i], rho), numformat=numformat)
        if data.form == "fs":
            for j in range(data.species_count):
                _write_rows(
                    fd,
                    _resample_values(data.r_grid, np.asarray(data.rho_values, dtype=float)[i, j], r),
                    numformat=numformat,
                )
        else:
            density = np.asarray(data.rho_values, dtype=float).diagonal(axis1=0, axis2=1).T[i]
            _write_rows(fd, _resample_values(data.r_grid, density, r), numformat=numformat)

    for i in range(data.species_count):
        for j in range(i + 1):
            if getattr(data, "rphi_values", None) is not None:
                pair = _resample_values(data.r_grid, np.asarray(data.rphi_values, dtype=float)[j, i], r)
            else:
                pair = r * _resample_values(data.r_grid, np.asarray(data.phi_values, dtype=float)[j, i], r)
            _write_rows(fd, pair, numformat=numformat)


def _write_adp_body(
    fd,
    data: ADPData,
    *,
    r_grid: np.ndarray,
    rho_grid: np.ndarray,
    numformat: str = "%.16e",
) -> None:
    _write_eam_body(fd, data, r_grid=r_grid, rho_grid=rho_grid, numformat=numformat)

    for i in range(data.species_count):
        for j in range(i + 1):
            r = np.asarray(r_grid, dtype=float)
            dipole = _resample_values(data.r_grid, np.asarray(data.dipole_values, dtype=float)[i, j], r)
            _write_rows(fd, dipole, numformat=numformat)

    for i in range(data.species_count):
        for j in range(i + 1):
            r = np.asarray(r_grid, dtype=float)
            quadrupole = _resample_values(data.r_grid, np.asarray(data.quadrupole_values, dtype=float)[i, j], r)
            _write_rows(fd, quadrupole, numformat=numformat)


def _write_tersoff_body(fd, data: TersoffData, *, numformat: str = "%.16e") -> None:
    labels = [str(symbol) for symbol in data.species]
    table = np.asarray(data.parameter_table, dtype=float)

    fd.write(
        "# Tersoff parameters fitted with ForgeFF\n"
        "# these entries are in LAMMPS \"metal\" units:\n"
        "#   A,B = eV; lambda1,lambda2,lambda3 = 1/Angstroms; R,D = Angstroms\n"
        "#   other quantities are unitless\n\n"
    )
    fd.write("# format of a single entry (one or more lines):\n")
    fd.write("#   element 1, element 2, element 3,\n")
    fd.write("#               m, gamma, lambda3, c, d, costheta0, n,\n")
    fd.write("#               beta, lambda2, B, R, D, lambda1, A\n\n")

    for i, left in enumerate(labels):
        for j, middle in enumerate(labels):
            for k, right in enumerate(labels):
                params = TersoffParameters(*map(float, table[i, j, k].tolist()))
                fd.write(f"{left:>2s} {middle:>4s} {right:>4s} ")
                fd.write(
                    " ".join(
                        f"{value:.16e}"
                        for value in (
                            params.m,
                            params.gamma,
                            params.lambda3,
                            params.c,
                            params.d,
                            params.h,
                            params.n,
                            params.beta,
                            params.lambda2,
                            params.B,
                            params.R,
                            params.D,
                            params.lambda1,
                            params.A,
                        )
                    )
                )
                fd.write("\n")


def write_lammps_potential(
    filename: str | Path,
    data: EAMData | ADPData | TersoffData,
    *,
    header: list[str] | None = None,
    lattice: list[str] | None = None,
    a: list[float] | None = None,
    mass: list[float] | None = None,
    nr: int | None = None,
    nrho: int | None = None,
) -> None:
    """Write an EAM/ADP potential to a LAMMPS-compatible file."""
    path = Path(filename)
    if isinstance(data, ADPData):
        if path.suffix != ".adp":
            raise ValueError("ADP export requires an output filename ending in .adp")
    elif isinstance(data, TersoffData):
        if path.suffix != ".tersoff":
            raise ValueError("Tersoff export requires an output filename ending in .tersoff")
        with open(path, "w", encoding="utf-8") as fd:
            _write_tersoff_body(fd, data)
        return
    elif data.form == "fs":
        if path.suffix != ".fs":
            raise ValueError("Finnis-Sinclair export requires an output filename ending in .fs")
    else:
        if not path.name.endswith(".eam.alloy"):
            raise ValueError("Alloy EAM export requires an output filename ending in .eam.alloy")

    r_grid = _uniform_grid(data.r_grid, nr)
    rho_grid = _uniform_grid(data.rho_grid, nrho)

    with open(path, "w", encoding="utf-8") as fd:
        _write_common_header(fd, data, r_grid=r_grid, rho_grid=rho_grid, header=header, lattice=lattice, a=a, mass=mass)
        if isinstance(data, ADPData):
            _write_adp_body(fd, data, r_grid=r_grid, rho_grid=rho_grid)
        else:
            _write_eam_body(fd, data, r_grid=r_grid, rho_grid=rho_grid)


def read_lammps_tersoff_potential(filename: str | Path) -> TersoffData:
    """Read a standard LAMMPS Tersoff potential file."""
    path = Path(filename)
    entries: "OrderedDict[tuple[str, str, str], list[float]]" = OrderedDict()
    with path.open("r", encoding="utf-8") as fd:
        content = [line.strip() for line in fd if line.strip() and not line.strip().startswith("#")]

    for line in content:
        fields = line.split()
        if len(fields) != 17:
            raise ValueError("The Tersoff file must contain 17 tokens per entry.")
        key = (fields[0], fields[1], fields[2])
        entries[key] = [float(value) for value in fields[3:]]

    if not entries:
        raise ValueError("The Tersoff potential file is empty.")

    species: list[str] = []
    for key in entries:
        for symbol in key:
            if symbol not in species:
                species.append(symbol)

    return TersoffData.from_parameter_dict(entries, species=species)
