"""Export tabulated potentials to LAMMPS-compatible files."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
from ase.data import atomic_masses, chemical_symbols

from forgeff.potentials.eam.adp_data import ADPData
from forgeff.potentials.eam.data import EAMData


def _species_labels(species: np.ndarray) -> list[str]:
    return [chemical_symbols[int(number)] for number in np.asarray(species, dtype=int).tolist()]


def _species_masses(species: np.ndarray) -> list[float]:
    return [float(atomic_masses[int(number)]) for number in np.asarray(species, dtype=int).tolist()]


def _species_lattice(species: np.ndarray, lattice: list[str] | None) -> list[str]:
    if lattice is not None:
        if len(lattice) != len(species):
            raise ValueError("Length of lattice metadata must match the number of species.")
        return list(lattice)
    return ["fcc"] * len(species)


def _species_a(species: np.ndarray, a: list[float] | None) -> list[float]:
    if a is not None:
        if len(a) != len(species):
            raise ValueError("Length of lattice constant metadata must match the number of species.")
        return [float(value) for value in a]
    return [1.0] * len(species)


def _write_rows(fd, values: np.ndarray, *, numformat: str = "%.16e", nc: int = 1) -> None:
    arr = np.asarray(values, dtype=float)
    if arr.ndim == 1:
        np.savetxt(fd, arr.reshape(-1, nc), fmt=nc * [numformat])
    else:
        np.savetxt(fd, arr.reshape(arr.shape[0], -1), fmt=arr.shape[1] * [numformat])


def _write_common_header(
    fd,
    data: EAMData | ADPData,
    *,
    header: list[str] | None = None,
    lattice: list[str] | None = None,
    a: list[float] | None = None,
    mass: list[float] | None = None,
) -> None:
    species = np.asarray(data.species, dtype=int)
    elements = _species_labels(species)
    masses = list(mass) if mass is not None else _species_masses(species)
    lattices = _species_lattice(species, lattice)
    a_values = _species_a(species, a)

    if header is None:
        header = [
            "LAMMPS setfl format generated by ForgeFF",
            "",
            "",
        ]
    if len(header) < 3:
        header = [*header, *([""] * (3 - len(header)))]
    for line in header[:3]:
        fd.write(f"{line}\n")

    fd.write(f"{len(elements)} {' '.join(elements)}\n")
    fd.write(
        f"{len(np.asarray(data.rho_grid, dtype=float))} {float(np.asarray(data.rho_grid, dtype=float)[1] - np.asarray(data.rho_grid, dtype=float)[0])} "
        f"{len(np.asarray(data.r_grid, dtype=float))} {float(np.asarray(data.r_grid, dtype=float)[1] - np.asarray(data.r_grid, dtype=float)[0])} "
        f"{float(np.asarray(data.r_grid, dtype=float)[-1])}\n"
    )


def _write_eam_body(fd, data: EAMData, *, numformat: str = "%.16e") -> None:
    r = np.asarray(data.r_grid, dtype=float)
    rho = np.asarray(data.rho_grid, dtype=float)
    species = np.asarray(data.species, dtype=int)
    masses = _species_masses(species)
    lattices = _species_lattice(species, None)
    a_values = _species_a(species, None)

    for i in range(data.species_count):
        fd.write(f"{int(species[i])} {masses[i]:f} {a_values[i]:f} {lattices[i]}\n")
        _write_rows(fd, np.asarray(data.emb_values, dtype=float)[i], numformat=numformat)
        if data.form == "fs":
            for j in range(data.species_count):
                _write_rows(fd, np.asarray(data.rho_values, dtype=float)[i, j], numformat=numformat)
        else:
            _write_rows(fd, np.asarray(data.rho_values, dtype=float).diagonal(axis1=0, axis2=1).T[i], numformat=numformat)

    for i in range(data.species_count):
        for j in range(i + 1):
            if getattr(data, "rphi_values", None) is not None:
                pair = np.asarray(data.rphi_values, dtype=float)[j, i]
            else:
                pair = r * np.asarray(data.phi_values, dtype=float)[j, i]
            _write_rows(fd, pair, numformat=numformat)


def _write_adp_body(fd, data: ADPData, *, numformat: str = "%.16e") -> None:
    _write_eam_body(fd, data, numformat=numformat)

    for i in range(data.species_count):
        for j in range(i + 1):
            _write_rows(fd, np.asarray(data.dipole_values, dtype=float)[i, j], numformat=numformat)

    for i in range(data.species_count):
        for j in range(i + 1):
            _write_rows(fd, np.asarray(data.quadrupole_values, dtype=float)[i, j], numformat=numformat)


def write_lammps_potential(
    filename: str | Path,
    data: EAMData | ADPData,
    *,
    header: list[str] | None = None,
    lattice: list[str] | None = None,
    a: list[float] | None = None,
    mass: list[float] | None = None,
) -> None:
    """Write an EAM/ADP potential to a LAMMPS-compatible file."""
    path = Path(filename)
    if isinstance(data, ADPData):
        if path.suffix != ".adp":
            raise ValueError("ADP export requires an output filename ending in .adp")
    elif data.form == "fs":
        if path.suffix != ".fs":
            raise ValueError("Finnis-Sinclair export requires an output filename ending in .fs")
    else:
        if not path.name.endswith(".eam.alloy"):
            raise ValueError("Alloy EAM export requires an output filename ending in .eam.alloy")

    r = np.asarray(data.r_grid, dtype=float)
    rho = np.asarray(data.rho_grid, dtype=float)
    if r.size < 2 or rho.size < 2:
        raise ValueError("EAM/ADP export requires at least two points on each grid.")

    with open(path, "w", encoding="utf-8") as fd:
        _write_common_header(fd, data, header=header, lattice=lattice, a=a, mass=mass)
        if isinstance(data, ADPData):
            _write_adp_body(fd, data)
        else:
            _write_eam_body(fd, data)
