[common]
seed = 42  # random seed

[configurations]
training = 'traning.cfg'  # original data for training
initial = 'initial.cfg'  # data to be evaluated
final = 'final.cfg'  # data with `MV_grade`

[potentials]
final = 'final.toml'

[grade]
mode = 'neighborhood'

[grade.maxvol]
algorithm = 'maxvol'  # {'maxvol', 'exaustive'}
