[common]
seed = 42  # random seed for initializing the potential parameters etc.

[configurations]
training = 'examples/toml/data/unary/training.cfg'

[potentials]
initial = 'initial.toml'
final = 'final.npy'

[loss]  # setting for the loss function
energy_weight = 1.0
forces_weight = 0.01
stress_weight = 0.001

# optimization steps

# style 1: simple
# steps = ['Nelder-Mead', 'BFGS']

# style 2: sophisticated
# "optimized" specifies which parameter groups are optimized at the step.
[[steps]]
method = 'Nelder-Mead'
optimized = ['parameters']
[steps.kwargs]
tol = 1e-7
[steps.kwargs.options]
maxiter = 1000

[[steps]]
method = 'BFGS'
optimized = ['parameters']
