[common]
seed = 42  # random seed for initializing MTP parameters
engine = 'cext'  # {'cext', 'numpy', 'numba', 'mlippy'}
species = [6, 1]  # atomic numbers corresponding to types

[configurations]
training = 'ase.xyz'

[potentials]
initial = 'initial.mtp'
final = 'final.mtp'

[loss]  # setting for the loss function
energy_weight = 1.0
forces_weight = 0.01
stress_weight = 0.01

[[steps]]
method = 'Level2MTP'
optimized = ['radial_coeffs']

[[steps]]
method = 'LLS'
optimized = ['moment_coeffs']

[[steps]]
method = 'BFGS'
optimized = ['radial_coeffs', 'moment_coeffs']
[steps.kwargs]
jac = true
tol = 1e-3
[steps.kwargs.options]
maxiter = 1000

[[steps]]
method = 'LLS'
optimized = ['moment_coeffs']
